### ISSUE TITLE
the default for www prefix should be add not drop

### ISSUE THREAD

**Issue by alexanderhaensch** [atelierdisko/hoi#1]
It is general best practice to redirect non-www to www.
There are several reasons:
http://www.yes-www.org/why-use-www/

**Comment by davidpersson** [comment]
This is kind of a philosophical question (there's also http://dropwww.com/why) ;)
It's true, if your project becomes really big, the www is preferred.  However, you probably than have other problems and would not use hoi. Throughout our projects we standardized on dropping the www. You can change it any time by overriding it in the domain directive.
