### ISSUE TITLE
Notify systemd if unit contents changed

### ISSUE THREAD

**Issue by mariuswilms** [atelierdisko/hoi#19]
When changing i.e. a command's "command" spec but keep the ID (the name) the contents of the resulting unit file will change. "systemctl start/restart" will still see the old unit. We'll need to notify systemd via "daemon-reload" or similar when a file changes.

todo: prove the problem exists and it's not due to a failing unload operation

**Comment by davidpersson** [comment]
Seems to randomly appear and disappear... systemctl daemin-reload && systemctl reset-failed will fix it nonetheless. Have the suspicion it's due to migration between hoi versions.

**Comment by davidpersson** [comment]
refs #21
